### ISSUE TITLE
Investigate SuiteSparse Performance

### ISSUE THREAD

**Issue by willow-ahrens** [willow-ahrens/FinchBenchmarks#47]
It appears that the SuiteSparse SpMV is a little slow. I'm not sure if this is because we're calling it incorrectly. The relevant code is here: https://github.com/willow-ahrens/FinchBenchmarks/blob/main/spmv/spmv_suite_sparse.jl.

**Comment by willow-ahrens** [comment]
@rayegun, do you see anything wrong with the way we are calling suitesparse here?

**Comment by rayegun** [comment]
My immediate question is whether you're expecting a full / dense output? You kind of have to trick the C library into doing the fastest dot product method.

**Comment by willow-ahrens** [comment]
what does that mean? you can see how we're calling it in the linked file. y and x are dense vectors, A is SparseMatrixCSC

**Comment by willow-ahrens** [comment]
@rayegun @DrTimothyAldenDavis The numbers we're getting are looking a little strange. Is this what you would expect for a single threaded Suitesparse SpMV?

https://github.com/willow-ahrens/FinchBenchmarks/blob/main/spmv/charts_lanka2/spmv_performance_(faster_than_taco).png

**Comment by rayegun** [comment]
Sorry I had the flu, I will try to get to this today.

**Comment by DrTimothyAldenDavis** [comment]
Also, if GrB_mxv is doing y=A*x with no accumulator then I have to compute the sparsity pattern of y even if x is dense. 

You need to do

y = 0 using GrB_assign to make y a dense all zero vector 

Then
y+=A*x

**Comment by willow-ahrens** [comment]
We did call `GrBVector(y)` where `y` is a dense julia vector, then we call julia `mul!`, is this the wrong approach?

**Comment by willow-ahrens** [comment]
https://github.com/willow-ahrens/FinchBenchmarks/blob/main/spmv/spmv_suite_sparse.jl

**Comment by rayegun** [comment]
The fastest way to check if that's the issue would be to add `accum=+` to the `mul!` as a kwarg

**Comment by willow-ahrens** [comment]
I see! It looks like the correct invocation is:
```
function spmv_suite_sparse_kernel(y, A, x) 
            y .= 0
            mul!(y, A, x; accum=+) 
        end
```
How do I set num threads?

**Comment by rayegun** [comment]
`gbset(:nthreads, 1)` should work.

The `y .= 0` might do the weird thing of making `y` into an "iso" array (a single scalar). @DrTimothyAldenDavis what's the fastest way to zero the matrix without changing the storage from full to iso full?

**Comment by rayegun** [comment]
Burble is `gbset(:burble, true)`. Not recommended in a benchmarking loop

**Comment by willow-ahrens** [comment]
okay, the performance is looking much better with the changes we have so far, we'll update with the new results once we have them. Thanks for your help!

**Comment by DrTimothyAldenDavis** [comment]
Do you also have a multi-threaded benchmark, or just a single-threaded one?

**Comment by willow-ahrens** [comment]
we don't have multi-threading ready for benchmarking just yet, but are hoping to get it going soon.

**Comment by willow-ahrens** [comment]
The results are still not looking normal here:
https://github.com/willow-ahrens/FinchBenchmarks/blob/main/spmv/charts/spmv_performance_(faster_than_taco).png

I'll check the burble.

**Comment by DrTimothyAldenDavis** [comment]
Yes, I'd like to see the burble.  I'm also curious if the difference in run time might have something to do with the Julia memory manager.  The creation of y as an iso-full vector, then non-iso, causes a free and a malloc in each iteration.  That's something I could avoid in the future.  It doesn't seem to have much effect on performance when using malloc/free directly from C, but maybe it's slower in Julia.  It would be more of an issue if the matrix is small, as well.  How big are these test matrices?

**Comment by willow-ahrens** [comment]
The names are listed, approximately 100_000 x 100_000 with 1_000_000 nnz. I'll get burbling

**Comment by DrTimothyAldenDavis** [comment]
Ok. That's the correct burble. My burble also includes the run time for each call. I suppose that is disabled in Julia. 

The single threaded case is not something I've extensively benchmarked. I'll have to check to see if there's something I'm doing that I can skip when using just one thread. 

Either that or perhaps there's some overhead in the Julia wrapper.

**Comment by willow-ahrens** [comment]
I see. In that case, I may use MKL for an spmv benchmark. We have a different benchmark that calls LAGraph, so it made some sense to call graphblas twice, but something seems amiss with the julia wrapper and I think we need a more predictable baseline.

**Comment by willow-ahrens** [comment]
Thank you so much for all your help!

**Comment by rayegun** [comment]
Last we measured wrapper overhead it was ~1-5%, and sometimes within benchmark noise.

**Comment by willow-ahrens** [comment]
yes, I agree it likely isn't the wrapper.

**Comment by DrTimothyAldenDavis** [comment]
OK.  It might be that my saxpy4 kernel isn't letting the compiler use a fused multiply-add, perhaps.  I'll have to explore its performance.  I've been getting good results as compared to the MKL for sparse-times-dense-vector, but that was a parallel benchmark.  I'm unsure about the single-thread case.

**Comment by DrTimothyAldenDavis** [comment]
Could you try compiling GraphBLAS in COMPACT mode and the JIT enabled, where there are no "factory kernels"?  The JIT kernel for this case may be faster, because I see an iso-test inside the deepest loop.  That becomes a constant (true or false) in the JIT, so the compiler should remove it.  In the FactoryKernel, it looks like `double aik = Ax [iso ? 0 : p]`, where iso is always true or always false, but that would not be known at compile time.

**Comment by rayegun** [comment]
I will give this a try tomorrow

**Comment by DrTimothyAldenDavis** [comment]
It would also be useful to see the timings of the individual calls to GrB methods, which normally appears at the end of each burble, like this for the GAP/Twitter matrix.  Note that my burble is different because of how I handle this case in my own MATLAB interface:

```
 [ GxB_Matrix_pack_FullC 
   3.81e-06 sec ]
 [ GrB_assign (pending: 0) Method 24: C = Z 
   0.282 sec ]
 [ GxB_Matrix_pack_CSC 
   4.05e-06 sec ]
 [ GxB_Matrix_pack_FullC 
   3.1e-06 sec ]
 [ GrB_mxm C=A*B, saxpy (saxpy4: F += S*F) (coarse, threads: 1) (C in place) 
   23.9 sec ]
```

These are small test matrices in your Finch benchmarks.  I'm guessing that my iso/non-iso flailing on the y vector is causing most of my slowdown, which could be relatively worse for small test matrices.  I tried revising my kernels so it more directly exposes the fused multiply-add, and removes the ternary test from inside the loop when A is iso, and such.  This didn't help, so I'm guessing my sparse-times-dense vector code itself is in good shape.  I just need to handle the y iso-to-non-iso-and-back-again case better.  I don't include that time in my burble; it's buried inside the saxpy4 kernel, where I call `GB_convert_any_to_non_iso`.

https://github.com/DrTimothyAldenDavis/GraphBLAS/blob/6680f9f5058f0afdb1730429867f2baec07a3b92/Source/GB_AxB_saxpy4.c#L127

`    GB_OK (GB_convert_any_to_non_iso (C, true)) ;`

An alternative explanation might be the size of the integers used in the sparse matrices.  I'm using 64-bit integer indices for all my matrices, but that's overkill.  If Finch is using 32-bit, then it would be faster, and that might explain the differences.
